### ISSUE TITLE
Simplify circleci config

### ISSUE THREAD

**Issue by Wirg** [sicara/sicarator#12]
We could use executors and other configs to simplify circleci config.

https://github.com/sicara/sicarator/blob/e70f4eaa758d26430fa4b15aa5b388e62382eb9b/generators/app/templates/ci/.circleci/config.yml#L7-L9

```
executors:
  base-python:
    working_directory: ~/myproject
    docker:
      - image: cimg/python:3.9.11
```

```
  isort:
    executor: base-python
```
