### ISSUE TITLE
Run the mypy pre-commit only on staged files

### ISSUE THREAD

**Issue by julienperichon** [sicara/sicarator#80]
By default, pre-commit gives only the staged files to each pre-commit command.

However, in Sicarator, we do the following:
```yaml
  - id: type-check
    name: Type checking (mypy)
    entry: make type-check
    pass_filenames: false
    language: system
    types: [python]
    stages: [commit]
```
with `make type-check` as 
```Makefile
type-check:
	poetry run mypy src
```

We could do something like this to run mypy only on staged files:
```yaml
  - id: type-check
    name: Type checking (mypy)
    entry: mypy
    language: system
    types: [python]
    stages: [commit]
```

@ywolff What do you think ?
